config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  post '/download' => 'users#down_load_avatar'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)

    if @user
      redirect_to @user
    else
      flash[:notice] = "Can't create new user !"
      redirect_to :new
    end

  end

  def edit
  end

  def new
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def index
    @users = User.all
  end

  def down_load_avatar
    user = User.find_by id: params[:id]
    # slice the string to get download link
    # before: /system/users/avatars/000/000/002/original/anh02.png?1479974141
    # after: /system/users/avatars/000/000/002/original/anh02.png
    origin_url = user.avatar.url.to_s
    image_url = origin_url.slice(0, origin_url.rindex('?'))

    image_url = File.join(Rails.root,"public", image_url)
    test_url = File.join(Rails.root,"public",user.avatar.url(:original, true))
    send_file(test_url,
              filename: "#{user.name}.png",
              type: "application/png")
  end

  private
    def user_params
      params.require(:user).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaperClip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>List all users and avatars</h1>
<hr>
<%@users.each do |user|%>
<strong>Name: <%=user.name%> | <%= link_to 'Download', download_path(id: user.id), method: :post%></strong> <br/>
<%end%>

app/views/users/new.html.erb
<%flash.each do |key, value|%>
<strong> <%=key%> : <%=value%></strong>
<hr>
<%end%>

<%= form_for :user, url: users_path, html: { multipart: true } do |form| %>
  <p>
  <%= form.label :name%>
  <%= form.text_field :name %>
  </p>
  <p>
  <%= form.file_field :avatar %>
  </p>
  <%= form.submit 'Post'%>
<% end %>

app/views/users/show.html.erb
<strong>Username: <%=@user.name%></strong>
<hr>
<%= image_tag @user.avatar.url %><br>
<%= image_tag @user.avatar.url(:medium) %><br>
<%= image_tag @user.avatar.url(:thumb) %> <br>

<hr>